version: '3.5'

services:
  app_cli:
    build:
      context: ./docker
    volumes:
      - .:/application/
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    command:
      - ./endless_process
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default: